apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: node-app-test
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app-test
  template:
    metadata:
      labels:
        app: node-app-test
    spec:
      containers:
        - name: node-app
          image: khatthaphone/node-app:v2
