version: "3.8"
services:
  todo-web:
    image: todo-web:v0.0.01
    links:
      - todo-api:todo-api
    ports:
      - 80:80
    environment:
      VUE_APP_TODO_API_URL: http://todo-api:9090
      VUE_APP_UPLOAD_API_URL: host.docker.internal:8080
  todo-api:
    image: todo-api:v0.0.01
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - 9090:9090
    restart: always
    environment:
      port: 9090
      todo_db_host: mysql
      todo_db_port: 3306
      todo_db_scheme: todo
      todo_db_user: todo
      todo_db_password: todo
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    volumes:
      - ./todo-db/init-sql:/docker-entrypoint-initdb.d
      - ./todo-db/mysql-data:/var/lib/mysql