version: "3.8"
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./todo-db/init-sql:/docker-entrypoint-initdb.d
      - ./todo-db/mysql-data:/var/lib/mysql